### ISSUE TITLE
Docker image not pushed to dockerhub

### ISSUE THREAD

**Issue by livanov93** [urmahp/ursim_docker#2]
`docker pull mahp2502/ursim_docker:5.11.1.108318` 
finishes with
`Error response from daemon: pull access denied for mahp2502/ursim_docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied `

docker login has been done and it works fine with all other docker images. 

Please check workflows, the image pushing part.

**Comment by fmauch** [comment]
I assume, that is is simply not accessible publicly? Clicking on the link in the README opens a page requireing logging in to dockerhub

**Comment by urmahp** [comment]
Yes currently it is private, which is why you cannot pull it. I don't know when the image will be made public yet.

**Comment by livanov93** [comment]
Thanks for clarification!
