### ISSUE TITLE
Unable to install urcap inside container

### ISSUE THREAD

**Issue by fmauch** [urmahp/ursim_docker#3]
I tried installing a urcap inside the container and was not able to finish this.

I launched the container using
```
docker run --rm -it -p 5900:5900 -p 29999:29999 -p 30001-30010:30001-30010 --name ursim -v "${HOME}/.ursim/programs:/ursim/programs" -v "${HOME}/.ursim/urcaps:/ursim/.urcaps" mahp2502/ursim_docker:5.11.1.108318
```

I copied my `externalcontrol-1.0.5.urcap` file to the program directory from which I could install it on the teach panel. After that, the file ´com.fzi.externalcontrol-1.0.5.jar` was present inside `/ursim/.urcaps` inside the container. When clicking "Restart" on the TP, the container ended (as expected). After restarting the container, I could not find any traces of the URCap on the TP. I verified, that the `.jar` file was still inside `/ursim/.urcaps` to make sure, my volumes are working correctly.

Additionally, the URCaps entry inside the Polyscope settings was "gone". Removing the `jar` file from the `/ursim/.urcaps` folder and restarting the container brought that back.

I don't really know how to progress from here.

**Comment by urmahp** [comment]
This also happens for me, not sure why this is happening, but I guess it has something to do with that the container ends when restarting the simulator. 

I will look into being able to restart the simulator without ending the docker, I think that it will fix this issue and then it should be possible to install the urcap in the way you are describing above. Once it is fixed I will also provide some documentation on how to use the docker together with a urcap.

**Comment by urmahp** [comment]
A workaround to install the URCap has been introduced in #6.

**Comment by urmahp** [comment]
Another approach to installing the urcap is documented in #7
